from pathlib import Path

# Base directory for audio files
AUDIO_DIR = Path("wav")

# speaker1 = {
#     str(AUDIO_DIR / "crab-story" / "split" / "wherewasi.wav"): "Alright, where was I?",
#     str(AUDIO_DIR / "crab-story" / "split" / "crimsonsun.wav"): "Ah yes, the crimson sun.",
#     str(AUDIO_DIR / "crab-story" / "split" / "aliens.wav"): "So these aliens had irridecent skin that rippled with every thought.",
#     str(AUDIO_DIR / "crab-story" / "split" / "harmonies.wav"): "And they spoke in harmonies instead of words.",
# }


maya = {
    str(AUDIO_DIR / "crab-story" / "mono_1.wav"): "OK fresh start, how about this... Close your eyes for a second.  Imagine a world made entirely of sand.  Gold and shimmering sand that stretches as far as the eye can see.  In this world, there is a tiny village made of polished shells.  And in that village lives a little sandcrap named Pip.  Pip dreams of exploring the world beyond his village, but everyone tells him its too dangerous.  One day pip finds an old, chipped compass.  He knows that compass holds the key to his adventure. What happens next?  Should we let pip follow his dream?",
    str(AUDIO_DIR / "crab-story" / "mono_2.wav"): "Alright, where was I?  Ah yes, the crimson sun.  So these aliens had irridecent skin that rippled with every thought.  And they spoke in harmonies instead of words.",
    str(AUDIO_DIR / "crab-story" / "mono_3.wav"): "If pip's bouncing off the shell walls with excitement, he probably wouldnt wait for a map or hidden tunnels.  hehehehe.  Hed probably grap that compass, yell Cya! to the other crabs and scurry out into the sand dunes as fast as his little legs could carry him.  ",
    str(AUDIO_DIR / "crab-story" / "mono_4.wav"): "Love blooms in the strangest places, right?  I bet pip never expected to find the same crab of his dreams, in the middle of a sandstorm.  But, maybe he does?   Or maybe he finds a love as stubborn and adventurous as he is.  Someone who appreciates a good mystery and isn't afraid to get a little sand in her gills.  Where do you see them meeting?  hm?",
}

melina = {
    # str(AUDIO_DIR / "melina" / "melina-01.wav"): "Did you want that to happen? It seems my worries were unfounded. Your Seamster, Bok, he is always eager to see your return. Hello. Other you, the flame of ruin lies just ahead. Hello. Other you, turning runes into strength. Spoken echoes linger here. So again? Old friend, I'm glad it was you I traveled with, to deliver you what is yours. Prevented by the mantle of barbs, I can take you to the Round Table Hold. There is something for which I must apologize. To commit a cardinal sin. Shall I turn your runes to strength? For that is their curse. Tell me when you are fully prepared.",
    str(AUDIO_DIR / "melina" / "melina-02.wav"): "As an ally by pact, in Marica's own words, I ask that you cease. I shall see to the kindling. Treat him with respect. Goodbye, Torrent. It is not to be meddled with. In Marica's own words, think not of the kindling. Destined death. We found her here after all. We might be together for some time, mean one behaves in such a manner. There is something I'd like to say. I'm sure he would be much contented, Seeker of the Elden Ring. We might be together for some time, where Mother gave me my purpose. We found him here after all. Goodbye, my companion. Tell me if you should change your mind. Then the Elden Ring beckons you. He wants someone to tell him he's beautiful.",
    # str(AUDIO_DIR / "melina" / "melina-03.wav"): "You have fought long and hard. I have long observed the lands between. I ask you, one more time, for bringing me to the base of the Urd Tree. The Urd Tree is close. I was born at the foot of the Urd Tree. Torrent had your measure from the very start. I must tender my thanks to Torrent, too. Our journey together ends here. Don't worry. It's not too late. It is a purpose which I choose to fulfill. My purpose was given to me by my mother. I see him crying, from time to time, yet I'm certain that we can reach an understanding. This world is in dire need of repair. The Lord of Frenzied Flame is no lord at all, a pity. You are no longer fit. I bequeath to you this ring, to face the challenge presented by the ring. All I ask of you is to make the journey. I wish to journey with you, once more, regardless of my mother's designs. Allow me a moment to converse with you. You are unable to enter the Urd Tree, no? But it must be done to reach the path beyond, amounting only to sacrifices. Though now, everything is lost to me. Summon me by grace, if you should reconsider. The Frenzied Flame is not to be meddled with, even if it does violate the Golden Order. The one who walks alongside Flame. Here, I can govern my own movement, traveler from beyond the fog. Life endures. Births continue. Let my hand rest upon you, for but a moment. I won't allow it.",
}

ana = {
    # str(AUDIO_DIR / "ana" / "ana01.wav"): "I mean, I've done some boxing or kickboxing, but not enough. These are disciplines that require a lot of time and years of study and training and all of that, and I have not done that. I'm Cuban, I was born in Havana, lived there until I was 18 years old, and then I moved to Madrid, and I still have my family there and my home, and I miss it every day. I love my country, yeah. I was so excited and so happy to be called for the follow-up in Ballerina. It's a spin-off of John Wick, and it happens between John Wick 3 and 4. In 2024, Ballerina is coming out, and I'm so excited. ",
    str(AUDIO_DIR / "ana" / "ana02.wav"): "And she's a beautiful hologram from the future, because I need it. I started this show when I was like 19, and I was playing a school student for three years, and I just felt like, oh, it's time to move on. I'm not really doing much more here. I've done everything I had to do, so it's time to go. And I asked them to kill me. No, I'm not left-handed, I'm right-handed. But I was told when I was little, I used to do more left-hand stuff. For some reason, my parents just got me used to the right hand. I think that's just wrong. I was nominated for an Oscar, and it was pretty incredible and very special, especially because I love the project. Blonde was a very unique movie and role for me, and it was wonderful to be recognized for that.",
    str(AUDIO_DIR / "ana" / "ana03.wav"): "Andrew is a very, is an incredible filmmaker and also very detailed and precise. And it was really important for him and me and every department to really nail these recreations. And so we had two monitors, our movie and then Marilyn's movie, and they were playing both at the same time. And if we didn't get it right, we had to do it again. I mean, it was so accurate that there was a moment where my hairstylist kept coming back and forth to me and the monitor to fix my hair. And she was, poor thing, doing so many trips that I just go with her to the monitor. I realized that she is looking at Marilyn's trying to fix my hair. ",
    # str(AUDIO_DIR / "ana" / "ana04.wav"): "So yeah, it is a testament to the art department and hair and makeup. Well, it was a pretty tough scene. Andrew didn't, you know, give me like a slow break in the eyes thing. We just went for a, you know, very long dialogue scene with the mother. So, you know, we didn't have any rehearsals. Andrew had never heard me speaking or moving like Marilyn. So I just went to set and I did this very intense scene and it was the first time for everyone to hear me and see me playing Marilyn and it was terrifying. I think this is a movie more about Norma Jean, the person who's, the woman who's been unseen, you know, this whole time. I feel like this photographic memory that we have of Marilyn's life, all these images that we've seen and we have an idea of what that story was. It's kind of like a take on that through her lens.",
    # str(AUDIO_DIR / "ana" / "darkwater.wav"): "You looked like you were having fun with Kelly Wilson. She's very attractive don't you think? You wanna fuck her? Finally some emotion! What do you wanna know? Where I was? What I did? Well now I know you're really full of shit. You wanna know if I'm fucking him? Ask me. You wanna know if he makes me cum? Or you wanna know how I make him cum? He left a bruise. You want to see? Or what... what? You going to divorce me? Look how assertive you've become. If I didn't know you I'd think you'd throw me on the floor and you'd fuck me. Ya? No.. you wouldn't do that.",
}

frolic = {
    str(AUDIO_DIR / "frolic.wav"): "The music was just the right volume, if I'm recalling it right. Not so loud I couldn't hear you, but just loud enough that you had to lean forward to angle your words directly into my ear. Your breath smelt like apple, and then coffee, then whichever drink you chose next. I can't be expected to remember everything. Mainly because by drink three, I was too horny to care about anything except you. By the time we got to that final cocktail, I was so desperate to take you home that all I could focus on was the intensity of your eyes, simultaneously shining in the neon and made dark by your desire. Somewhere in the middle of the second cocktail, just after I told you I felt hot from the way you were staring, that's when you reached for the ice. Just one cube, whipped quickly from the bucket behind the counter when the bartender's back was turned.",
}
